### PR TITLE
Support LR7.4+

### PR DESCRIPTION
**Pull request by ghenadiibatalski**
Make Plugin Compatible with LR 7.4+

### CODE REVIEW

**Comment by ghenadiibatalski** [comment]
closes #23

**Comment by ghenadiibatalski** [comment]
@evernat at least starts without problems and display something meaningful

**Comment by ghenadiibatalski** [comment]
repo looks to be dead?..

**Comment by bitsky6** [comment]
JDBC monitoring still not working with this liferay.

**Pull request merged**
